# ---
# - name: Configure CI server
#   hosts: aws_server
#   become: yes
#   become_method: sudo

#   tasks:
- name: apt-get update
  apt: update_cache=yes

- name: Installing Git
  apt: name=git state=present

# - name: Installing Java (1/3) - add repo for java 8
#   apt_repository: repo='ppa:webupd8team/java' state=present

# - name: Installing Java (2/3) - set licence selected and seen
#   debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
#   become: yes

# - name: Installing Java (3/3) - install java 8
#   apt: name=oracle-java8-installer state=latest update-cache=yes force=yes
#   become: yes

- name: Installing Maven
  apt: name=maven state=present

- name: Installing Jenkins (1/2) - copy script
  copy: src=install_jenkins.sh dest=./install_jenkins.sh mode=0777

- name: Installing Jenkins (2/2) - run script
  command: bash install_jenkins.sh

# It's important to run Jenkins first before modyfing the config
- name: Start and enable Jenkins
  service: name=jenkins state=started enabled=yes

- name: Disable Security(1/2) - Configure JVM Arguments
  copy: src=jenkins_default dest=/etc/default/jenkins owner=root group=root  mode=0666

  # remeber to chmod locally first
- name: Disable Security(2/2) - Replacing Jenkins config
  copy: src=config.xml dest=/var/lib/jenkins/config.xml owner=jenkins group=jenkins mode=0666

  # It'a also important to restart fisrt, and install plug after jenkins runing
- name: Restart Jenkins
  service: name=jenkins state=restarted

- name: Wait Jenkins Runing again...
  uri: url="http://localhost:6060" status_code=200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1

- name: Config Jenkins (1/3) - copy all jenkins configurations
  copy: src=jenkins.tar.gz dest=./jenkins.tar.gz owner=jenkins group=jenkins

- name: Config Jenkins (2/3) - copy script
  copy: src=config_jenkins.sh dest=./config_jenkins.sh mode=0777

- name: Create Job to Build Repo (3/3) - run script
  command: bash config_jenkins.sh

# - name: Install GitHub plugin
#   jenkins_plugin: name=github state=present

# - name: Install Maven plugin
#   jenkins_plugin: name=pipeline-maven state=present

- name: Restart Jenkins
  service: name=jenkins state=restarted

- name: Wait Jenkins Runing again...
  uri: url="http://localhost:6060" status_code=200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1


# - name: Create Job to Build Repo (1/3) - copy job.xml
#   copy: src=./job.xml dest=./job.xml owner=jenkins group=jenkins mode=0644

# - name: Create Job to Build Repo (2/3) - copy script
#   copy: src=./job.sh dest=./job.sh mode=0777

# - name: Create Job to Build Repo (3/3) - run script
#   command: bash job.sh
